### PR TITLE
Add wrapper for dss

### PR DESCRIPTION
**Pull request by KristofferC**
This is a work in progress to implement the direct sparse solver (DSS) interface in MKL.

What is left to do are the following:

- [X] Make it work for complex types.
- [X] Add and test `Ac_ldiv_B`
- [X] Try to run the positive definite solver and in case of zero pivots, fall back to indefinite matrix. Same as [in Base]( https://github.com/JuliaLang/julia/blob/f36ccf03148639d4e11c27e3017cd3b68302a968/base/sparse/linalg.jl#L633). What is weird is that when I run the pos def solver for an indefinite matrix I get a written warning about a zero pivot, but the actual error number being returned from the function does not correspond to a pos def error:
```julia
MKL-DSS-DSS-Error, Zero pivot detected
ERROR: LoadError: LoadError: MKLSparse.DSS.MKL_DSS_Exception("MKL_DSS_TERM_LVL_ERR")
 in dss_factor! at /home/kristoffer/.julia/v0.4/MKLSparse/src/DSS/dss_generator.jl:44
```

Why isn't this error number being returned: https://github.com/JuliaSparse/MKLSparse.jl/compare/master...KristofferC:kc/dss_wrap?expand=1#diff-ff085b6f0a82086cc72fcf0c4e22d52aR77

- [ ] Add methods for dealing with `Symmetric{T, SparseMatrixCSC{T, Ti}}`

Any comments or remarks on this WIP is of course appreciated.

### CODE REVIEW

**Comment by KristofferC** [comment]
A general question. Is there anything you specially need to do to enable threading in BLAS when having built Julia with MKL.

With the standard OpenBLAS build I get
```julia
julia> peakflops()
9.101030781608696e10
```

but with the MKL build it is much slower (only using one core):
```julia
julia> peakflops()
9.101030781608696e10
```

Is it needed to go thehttps://software.intel.com/en-us/node/471134 route?

**Comment by KristofferC** [comment]
Updated a bit.

**Comment by KristofferC** [comment]
I will probably refactor this a bit so it works similar to base where there is a factorize function that returns a `Factor` object and then you use that to solve instead of doing everything in one function like I am doing now. This is to make it possible to solve for many different RHS with the same factorization where the new RHS might be dependent on the previous solution.

**Comment by dmbates** [comment]
Shall I go ahead and merge the pull request now?  You can do the refactoring on a branch in this repository if that would be more convenient.

**Comment by KristofferC** [comment]
Yeah, makes sense.

**Pull request merged**
