### PR TITLE
Add factorization methods

### PR DESCRIPTION
**Pull request by KristofferC**
This implements the functionality that `factorize(A)` now gives a `Factor` type which can be used to solve equations.

One concern is that the garbage collector currently does not know how much memory a `Factor` type actually represents, same as commented here: https://github.com/JuliaLang/julia/issues/11698#issuecomment-111702530

Maybe [`dss_statistics`](https://software.intel.com/en-us/node/470322) can be used to get the memory consumption and then use [`jl_gc_count_allocd`](https://github.com/JuliaLang/julia/blob/84f14d1e6a6650f75506e5ec9b6d9bcdd64e168c/src/gc.c#L965) to add it.

### CODE REVIEW

**Comment by andreasnoack** [comment]
Great. I'd prefer to have an interface similar to that in base where you select the factorization you are interested in through the function name, i.e. `cholfact`, `ldltfact` and `lufact` and give an error if it is not possible to perform the factorization. On top of that you could then also have `factorize` that checks the matrix and decides.

Could you check the interface to see if it is possible to provide custom allocation function pointers. I've implemented gc tracked allocator functions with the usual libc API and used them with success for the CHOLMOD wrappers so they could also be used here if the library allows.

**Comment by KristofferC** [comment]
I agree, splitting into different factorization methods makes sense. Should there be different factorization types depending on what factorization was used (like in Base)? 

Regarding custom allocators, I have tried my best googling I haven't found anything about it.

**Comment by andreasnoack** [comment]
I think it is fine to use the same type. It is what we do right now for `CHOLMOD` which returns `Factor` for both `cholfact` and `ldltfact`.

**Comment by KristofferC** [comment]
I updated a bit, now `factorize` looks similar to base and there are three factorization methods.

**Comment by KristofferC** [comment]
Is it only for me MKL is very slow?

```julia
N = 4
A = sprand(9^N, 9^N, 0.001) + speye(9^N, 9^N)
A = A'A
b = rand(9^N)
x = similar(b)
@time cholfact(A) # 1.14 sec
@time MKLSparse.DSS.cholfact(A) # 3.63 sec
``

**Comment by andreasnoack** [comment]
I don't see a difference as large as that, but for matrices with similar structures CHOLMOD seems to be consistently faster than DSS. We should try some of the matrices from Tim Davis' library to see if this is different for sparse matrices with a different structure.

**Comment by andreasnoack** [comment]
MKL is usually using threads by default.

**Pull request merged**
